spring:
  datasource:
    url: jdbc:mysql://mysql_db:3306/spring_security?useSSL=false&allowPublicKeyRetrieval=true
    username: spring_security_user
    password: spring_security_password
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
crypto:
  aes256:
    key: KXL0G3w4Rfor4sbXpPD8fl8T02mUJwaw
    iv: uMDdtiDiy6p7eQRy

jwt:
  key-set:
    keys:
      - kid: kid-1
        secretKey: cxpoi2thr0w0gxgrz0w4yj59v7kk4sae
      - kid: kid-2
        secretKey: oyuq98vmooc59h1iwfhb6kgczyt71p21
