spring:
  datasource:
    url: jdbc:mysql://mysql_db:3306/spring_security?useSSL=false&allowPublicKeyRetrieval=true
    username: spring_security_user
    password: spring_security_password
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
